### ISSUE TITLE
Broken "link" in OpenShift Topology View

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat-operator#228]
![topology-view](https://user-images.githubusercontent.com/3787464/127353360-173f93ce-298b-4bdc-bbb4-a98513cbee8b.png)

![topology-view](https://user-images.githubusercontent.com/3787464/127352669-f3564101-a7c5-4a52-aa98-0e30de939f09.png)

Top is an older screenshot, from https://developers.redhat.com/blog/2021/01/25/introduction-to-containerjfr-jdk-flight-recorder-for-containers#deploying_containerjfr_on_red_hat_openshift . Bottom is the current state after a `make deploy_bundle` and graphically creating a Cryostat CR in the OpenShift Console, using the Operator git tag v1.0.0.

**Comment by andrewazores** [comment]
Related to #163?

**Comment by ebaron** [comment]
I think the cause of this bug is this line:
https://github.com/cryostatio/cryostat-operator/blob/deb0ee1bac6eefc92945c36fa2676da6e3169a8a/internal/controllers/common/resource_definitions/resource_definitions.go#L136

The operator deployment was renamed from `cryostat-operator` to `cryostat-operator-controller-manager` when we upgraded to Operator SDK 1.0.
