### ISSUE TITLE
Cryostat environment variables should be configurable

### ISSUE THREAD

**Issue by ebaron** [cryostatio/cryostat-operator#278]
We should allow the user to supply environment variables to the Cryostat deployment, either by adding them individually to the Cryostat CRD where it makes sense, or by accepting an arbitrary list of environment variables in the CRD.

**Comment by ebaron** [comment]
Not all environment variables used by Cryostat should be configurable with the operator. Some, like volume mounts, must continue to be controlled by the operator to ensure proper functioning. Selected environment variables should be added as separate properties in the Cryostat CRD `spec`.

**Comment by jan-law** [comment]
Hey Elliott! I was wondering which environment variables you were thinking of making configurable with this issue?

I remembered the team mentioned during the release planning meeting that port numbers, memory, and enabling/disabling TLS should be made configurable. Since then, it looks like you've made all of the above configurable with `serviceOptions`, `storageOptions`, and `spec.tls` in the Cryostat CRD.

Besides the env vars related to jfr-datasource urls and file system paths, it seems like the remaining hardcoded env vars in the operator are either 1) constants that probably shouldn't be modifiable (eg `CRYOSTAT_PLATFORM`), 2) SSL variables which already rely on `DISABLE_SERVICE_TLS` from `spec.tls`, or 3) related to the command channel hostname/port. 

Are there any existing variables that I missed? Or did you mean to add more variables in addition to the existing ones?

**Comment by andrewazores** [comment]
`CRYOSTAT_MAX_WS_CONNECTIONS` should be configurable, and `CRYOSTAT_REPORT_GENERATION_MAX_HEAP` should also be configurable even though it is only meaningful for deployments with 0 reports sidecar replicas. `CRYOSTAT_TARGET_CACHE_[SIZE|TTL]` also seem like they should be configurable.

**Comment by ebaron** [comment]
Good suggestions. I think this class has a good collection of environment variables used by Cryostat: https://github.com/cryostatio/cryostat/blob/6c4ab056a3246d0e24fd383ab534c2b7e1585363/src/main/java/io/cryostat/configuration/Variables.java

@andrewazores What about `CRYOSTAT_ALLOW_UNTRUSTED_SSL`. We currently always set this to true, but that doesn't seem right.

**Comment by ebaron** [comment]
Also, thank you @jan-law for taking this on!

**Comment by andrewazores** [comment]
> Good suggestions. I think this class has a good collection of environment variables used by Cryostat: https://github.com/cryostatio/cryostat/blob/6c4ab056a3246d0e24fd383ab534c2b7e1585363/src/main/java/io/cryostat/configuration/Variables.java
> 
> @andrewazores What about `CRYOSTAT_ALLOW_UNTRUSTED_SSL`. We currently always set this to true, but that doesn't seem right.

That's a good one too. That variable is used when Cryostat makes HTTPS requests out to other (micro)services - so, when it sends data to the jfr-datasource or to the reports sidecar. Since the Operator should be setting that up nicely with cert-manager with certificates that we can know about in advance and trust, we should be able to set that variable to `false` in most cases.

**Comment by jan-law** [comment]
> Since the Operator should be setting that up nicely with cert-manager with certificates that we can know about in advance and trust, we should be able to set that variable to `false` in most cases.

I can make `CRYOSTAT_ALLOW_UNTRUSTED_SSL` false by default if users don't specify a value, and mention in `config.md` that users can set this value to `true` if they want to allow recording uploads with an untrusted SSL cert.

**Comment by ebaron** [comment]
I wonder if `CRYOSTAT_ALLOW_UNTRUSTED_SSL=true` would ever be needed. jfr-datasource doesn't use HTTPS. The reports sidecar doesn't yet, but Cryostat talks to it using the internal service hostname whose certificates would be managed by cert-manager.

**Comment by ebaron** [comment]
> > The reports sidecar doesn't yet, but Cryostat talks to it using the internal service hostname whose certificates would be managed by cert-manager.
> 
> What would happen if a user disabled cert-manager with `enableCertManager: false`?

In this case, Cryostat and the reports deployment would communicate over plain HTTP.

**Comment by jan-law** [comment]
> I wonder if CRYOSTAT_ALLOW_UNTRUSTED_SSL=true would ever be needed.

If there's no configuration that requires this env var anymore, I can create an issue/PR to remove `CRYOSTAT_ALLOW_UNTRUSTED_SSL` from both the -operator and -base projects. Thoughts?

**Comment by ebaron** [comment]
> If there's no configuration that requires this env var anymore, I can create an issue/PR to remove `CRYOSTAT_ALLOW_UNTRUSTED_SSL` from both the -operator and -base projects. Thoughts?

It might be useful to keep in Cryostat, for non-operator-controlled deployments, but it sounds like it can be removed from the operator. @andrewazores does that seem right?

**Comment by andrewazores** [comment]
Related to #277
