### ISSUE TITLE
Create OAuthClient resource

### ISSUE THREAD

**Issue by jan-law** [cryostatio/cryostat-operator#289]
The `OAuthClient` resource in OpenShift should be created by the Operator, which can generate and store the client secret and then use that to create the resource. If it's needed it can also supply it to Cryostat, either by mounting the secret as a volume to the Cryostat container or by populating an environment variable with it, etc.

_Originally posted by @andrewazores in https://github.com/cryostatio/cryostat/issues/717#issuecomment-954791706_

**Comment by ebaron** [comment]
Excellent. Although it may change in the future, the operator works with a single namespace. So we would want the service account option. The operator already creates a service account for the Cryostat deployment, so that may help: https://github.com/cryostatio/cryostat-operator/blob/1708d3c1ea6f9a5be1160aea5672550aa1df6a85/internal/controllers/common/resource_definitions/resource_definitions.go#L771
