### ISSUE TITLE
Support AllNamespaces install mode

### ISSUE THREAD

**Issue by ebaron** [cryostatio/cryostat-operator#502]
We want to move to a model where the operator can manage multiple Cryostat installations in across different namespaces. In order to do this, we should support the AllNamespaces install mode, where the operator watches its CRs in all namespaces.

In addition, this will help prepare us for the next generation of OLM APIs: https://github.com/operator-framework/operator-lifecycle-manager/issues/2437.

**Comment by andrewazores** [comment]
See https://github.com/cryostatio/cryostat/pull/1290 . The Cryostat server now supports querying for discovery across namespaces if the right environment variable is set. This doesn't add any enhanced permissions model to ensure that users should have access to targets or archived recording files, so it would still rely on the Operator to create instances with the right Roles/Rolebindings as specified by the user's configuration (via multiple Cryostat CRs). It's then on the user to create configurations that make sense so that the Cryostat CRs correspond to meaningfully grouped users with similar roles and permissions levels.
